import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
	variable: "--font-nunito",
	subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mohol's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/m.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<body
				className={` ${nunito.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Header />
				{children}
				<Toaster position="top-right" />
			</body>
		</html>
  );
}
